blank_issues_enabled: false
contact_links:
  - name: ドキュメント
    url: https://github.com/takezou621/repairgpt/tree/main/docs
    about: プロジェクトのドキュメントを参照
  - name: ディスカッション
    url: https://github.com/takezou621/repairgpt/discussions
    about: 質問や一般的な議論はこちら
  - name: セキュリティ問題の報告
    url: https://github.com/takezou621/repairgpt/security/policy
    about: セキュリティ脆弱性の報告はこちら