name: Claude Night Automation

on:
  schedule:
    # 夜間のみ実行 (23:00, 02:00, 05:00 JST)
    - cron: '0 14,17,20 * * *'  # UTC時間
  workflow_dispatch:

jobs:
  night-automation:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      issues: write
      actions: read
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        fetch-depth: 0
        ref: main
    
    - name: Night Automation Processing
      uses: actions/github-script@v7
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          console.log('🌙 NIGHT AUTOMATION START');
          const now = new Date();
          console.log(`Execution time: ${now.toISOString()}`);
          
          try {
            // 全オープンIssueを取得
            const issues = await github.rest.issues.listForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'open',
              per_page: 50
            });
            
            console.log(`Found ${issues.data.length} open issues`);
            
            // claude-processedラベルがあるIssueを検索
            const processedIssues = issues.data.filter(issue => 
              issue.labels.some(label => label.name === 'claude-processed')
            );
            
            console.log(`Found ${processedIssues.length} Claude-processed issues`);
            
            if (processedIssues.length === 0) {
              console.log('No Claude-processed issues found, ending');
              return;
            }
            
            for (const issue of processedIssues) {
              console.log(`\n🔍 Processing Issue #${issue.number}: ${issue.title}`);
              
              try {
                // 関連ブランチを検索
                const branches = await github.rest.repos.listBranches({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  per_page: 100
                });
                
                const claudeBranches = branches.data.filter(branch => 
                  branch.name.includes(`issue-${issue.number}`) ||
                  branch.name.includes(`claude`) && branch.name.includes(`${issue.number}`)
                );
                
                if (claudeBranches.length === 0) {
                  console.log(`No Claude branch found for Issue #${issue.number}`);
                  continue;
                }
                
                const claudeBranch = claudeBranches[0];
                console.log(`Found branch: ${claudeBranch.name}`);
                
                // 既存PRをチェック
                const existingPRs = await github.rest.pulls.list({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  head: `${context.repo.owner}:${claudeBranch.name}`,
                  state: 'all'
                });
                
                let prNumber = null;
                
                if (existingPRs.data.length > 0) {
                  const pr = existingPRs.data[0];
                  console.log(`Found existing PR #${pr.number}, state: ${pr.state}`);
                  
                  if (pr.state === 'open') {
                    prNumber = pr.number;
                  } else {
                    console.log(`PR #${pr.number} is already ${pr.state}`);
                    continue;
                  }
                } else {
                  // PRを作成
                  console.log(`📝 Creating PR for Issue #${issue.number}`);
                  
                  try {
                    const pr = await github.rest.pulls.create({
                      owner: context.repo.owner,
                      repo: context.repo.repo,
                      title: `fix: ${issue.title} (closes #${issue.number})`,
                      head: claudeBranch.name,
                      base: 'main',
                      body: `## 🌙 夜間自動化処理

### 関連Issue
Closes #${issue.number}

### 自動化フロー
- [x] ✅ Claude Code実装検知
- [x] ✅ 夜間自動PR作成
- [x] ✅ 自動マージ実行
- [x] ✅ Issue自動クローズ
- [x] ✅ ブランチ自動削除

### 実行時刻
${now.toISOString()}

---
🌙 **Night Automation** | Generated with Claude Code Max`
                    });
                    
                    prNumber = pr.data.number;
                    console.log(`✅ Created PR #${prNumber}`);
                    
                  } catch (prError) {
                    console.log(`❌ PR creation failed: ${prError.message}`);
                    continue;
                  }
                }
                
                // PRマージ処理
                if (prNumber) {
                  console.log(`🔄 Auto-merging PR #${prNumber}`);
                  
                  // マージ前に短時間待機
                  await new Promise(resolve => setTimeout(resolve, 3000));
                  
                  try {
                    await github.rest.pulls.merge({
                      owner: context.repo.owner,
                      repo: context.repo.repo,
                      pull_number: prNumber,
                      commit_title: `Night Auto-merge: Issue #${issue.number}`,
                      merge_method: 'squash'
                    });
                    console.log(`✅ Merged PR #${prNumber}`);
                  } catch (mergeError) {
                    console.log(`⚠️ Merge failed: ${mergeError.message}`);
                    continue;
                  }
                }
                
                // Issue完了処理
                console.log(`🔒 Closing Issue #${issue.number}`);
                
                await github.rest.issues.createComment({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  issue_number: issue.number,
                  body: `🌙 **夜間自動化処理完了**

Issue #${issue.number} の夜間自動化が完了しました。

**実行内容:**
- 🤖 Claude Code実装検知
- 📝 自動PR作成・マージ
- 🔒 Issue自動クローズ
- 🧹 ブランチ自動削除

**実行時刻:** ${now.toISOString()}

---
🌙 **Night Automation Success** | Generated with Claude Code Max`
                });
                
                await github.rest.issues.update({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  issue_number: issue.number,
                  state: 'closed'
                });
                
                await github.rest.issues.addLabels({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  issue_number: issue.number,
                  labels: ['claude-completed', 'night-automation']
                });
                
                // ブランチ削除
                await new Promise(resolve => setTimeout(resolve, 2000));
                
                try {
                  await github.rest.git.deleteRef({
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    ref: `heads/${claudeBranch.name}`
                  });
                  console.log(`🗑️ Deleted branch ${claudeBranch.name}`);
                } catch (deleteError) {
                  console.log(`⚠️ Branch deletion failed: ${deleteError.message}`);
                }
                
                console.log(`🎯 Issue #${issue.number} NIGHT AUTOMATION COMPLETED!`);
                
              } catch (issueError) {
                console.log(`❌ Issue #${issue.number} processing failed: ${issueError.message}`);
                continue;
              }
            }
            
            console.log('\n🌙 NIGHT AUTOMATION FINISHED');
            
          } catch (error) {
            console.log(`❌ Night automation error: ${error.message}`);
            console.log(error.stack);
            throw error;
          }