name: Claude Ultimate Automation

on:
  # schedule:
  #   - cron: '*/1 * * * *'  # 毎分実行 - 無効化
  workflow_dispatch:  # 手動実行のみ
  # push:
  #   branches: ['claude/**']  # 無効化

jobs:
  ultimate-automation:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      issues: write
      actions: read
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        fetch-depth: 0
        ref: main
    
    - name: Ultimate Issue Processing
      uses: actions/github-script@v7
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          console.log('🚀 ULTIMATE AUTOMATION START');
          
          try {
            // 全オープンIssueを取得
            const issues = await github.rest.issues.listForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'open',
              per_page: 100
            });
            
            console.log(`Found ${issues.data.length} open issues`);
            
            // claude-processedラベルがあるIssueを検索
            const processedIssues = issues.data.filter(issue => 
              issue.labels.some(label => label.name === 'claude-processed')
            );
            
            console.log(`Found ${processedIssues.length} Claude-processed issues`);
            
            for (const issue of processedIssues) {
              console.log(`\n🔍 Processing Issue #${issue.number}: ${issue.title}`);
              
              // 関連ブランチを検索
              const branches = await github.rest.repos.listBranches({
                owner: context.repo.owner,
                repo: context.repo.repo,
                per_page: 100
              });
              
              const claudeBranch = branches.data.find(branch => 
                branch.name.includes(`issue-${issue.number}`) ||
                branch.name.includes(`${issue.number}`)
              );
              
              if (!claudeBranch) {
                console.log(`No branch found for Issue #${issue.number}`);
                continue;
              }
              
              console.log(`Found branch: ${claudeBranch.name}`);
              
              // 既存PRをチェック
              const existingPRs = await github.rest.pulls.list({
                owner: context.repo.owner,
                repo: context.repo.repo,
                head: `${context.repo.owner}:${claudeBranch.name}`,
                state: 'all'
              });
              
              if (existingPRs.data.length > 0) {
                const pr = existingPRs.data[0];
                console.log(`Found existing PR #${pr.number}, state: ${pr.state}`);
                
                if (pr.state === 'open') {
                  // オープンPRを自動マージ
                  console.log(`🔄 Auto-merging PR #${pr.number}`);
                  
                  try {
                    await github.rest.pulls.merge({
                      owner: context.repo.owner,
                      repo: context.repo.repo,
                      pull_number: pr.number,
                      commit_title: `Ultimate Auto-merge: Issue #${issue.number}`,
                      merge_method: 'squash'
                    });
                    console.log(`✅ Merged PR #${pr.number}`);
                  } catch (mergeError) {
                    console.log(`⚠️ Merge failed: ${mergeError.message}`);
                    continue;
                  }
                }
              } else {
                // PRを作成
                console.log(`📝 Creating PR for Issue #${issue.number}`);
                
                try {
                  const pr = await github.rest.pulls.create({
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    title: `fix: ${issue.title} (closes #${issue.number})`,
                    head: claudeBranch.name,
                    base: 'main',
                    body: `## 🤖 究極完全自動化
          
          ### 関連Issue
          Closes #${issue.number}
          
          ### 自動化フロー
          - [x] ✅ Claude Code実装完了
          - [x] ✅ 自動PR作成
          - [x] ✅ 即座に自動マージ
          - [x] ✅ Issue自動クローズ
          - [x] ✅ ブランチ自動削除
          
          ---
          🚀 **究極の100%完全自動化** | Generated with Claude Code Max`
                  });
                  
                  console.log(`✅ Created PR #${pr.data.number}`);
                  
                  // 即座にマージ
                  await new Promise(resolve => setTimeout(resolve, 2000));
                  
                  await github.rest.pulls.merge({
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    pull_number: pr.data.number,
                    commit_title: `Ultimate Auto-merge: Issue #${issue.number}`,
                    merge_method: 'squash'
                  });
                  
                  console.log(`✅ Auto-merged PR #${pr.data.number}`);
                  
                } catch (prError) {
                  console.log(`❌ PR creation/merge failed: ${prError.message}`);
                  continue;
                }
              }
              
              // Issue完了処理
              console.log(`🔒 Closing Issue #${issue.number}`);
              
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: issue.number,
                body: `🎉 **究極完全自動化フロー実行完了**
          
          Issue #${issue.number} の処理が100%自動で完了しました。
          
          **実行内容:**
          - 🤖 Claude Code Max実装検知
          - 📝 自動PR作成・マージ
          - 🔒 Issue自動クローズ
          - 🧹 ブランチ自動削除
          
          **実行時刻:** $(date)
          
          ---
          🚀 **真の100%完全自動化達成** | Ultimate Automation`
              });
              
              await github.rest.issues.update({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: issue.number,
                state: 'closed'
              });
              
              await github.rest.issues.addLabels({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: issue.number,
                labels: ['claude-completed', 'ultimate-automation']
              });
              
              // ブランチ削除
              await new Promise(resolve => setTimeout(resolve, 3000));
              
              try {
                await github.rest.git.deleteRef({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  ref: `heads/${claudeBranch.name}`
                });
                console.log(`🗑️ Deleted branch ${claudeBranch.name}`);
              } catch (deleteError) {
                console.log(`⚠️ Branch deletion failed: ${deleteError.message}`);
              }
              
              console.log(`🎯 Issue #${issue.number} ULTIMATE AUTOMATION COMPLETED!`);
            }
            
            console.log('\n🚀 ULTIMATE AUTOMATION FINISHED');
            
          } catch (error) {
            console.log(`❌ Ultimate automation error: ${error.message}`);
            console.log(error.stack);
          }